### ISSUE TITLE
How to determine the hyper-parameters?

### ISSUE THREAD

**Issue by ghost** [guoyang9/NCF#10]
In the original paper, the author said he used a randomly sampled one interaction for each user as the validation data, but in your code, you just used test data as the validation data, so I feel confused. Does that mean you used that test data to select the best parameters?

**Comment by guoyang9** [comment]
I agree with you. Simply tuning the parameters based on the performance of testing data could lead to overfitting problem. 
However, if you read the original [keras implementation](https://github.com/hexiangnan/neural_collaborative_filtering), you would find no validation phrase, either. Therefore I removed the parameter searching part since the sampled interaction raises much uncertainty.
